"""update users table

Revision ID: 2b26b997a1ea
Revises: 3d1c68d20419
Create Date: 2023-09-17 14:55:29.431207

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '2b26b997a1ea'
down_revision: Union[str, None] = '3d1c68d20419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
