"""changed creating and updating date users table

Revision ID: ef762a1b8189
Revises: 1796f6ff5f82
Create Date: 2023-09-17 15:29:28.548656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef762a1b8189'
down_revision: Union[str, None] = '1796f6ff5f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
